# -*- coding: utf-8 -*-
"""HTML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_q_5h-5yk3zcR-Bhn71dAGwv48fGBgGt

### **What is HTML?**  
HTML (**HyperText Markup Language**) is the basic language used to create webpages. It helps in structuring content like text, images, links, and forms.  

### **How to Start Using HTML?**  
1️⃣ Open a text editor (Notepad, VS Code, etc.).  
2️⃣ Save the file with `.html` extension (e.g., `index.html`).  
3️⃣ Type `html:5` and press **Enter** (in VS Code) or manually write the following:  

```html
<!DOCTYPE html>
<html>
<head>
    <title>My First Webpage</title>
</head>
<body>
    <h1>Welcome to My Page</h1>
</body>
</html>
```
4️⃣ Open the file in a browser to see your webpage. 🎉  

---

### **Basic HTML Tags (Step-by-Step)**  
🔹 **Headings:** Used for titles (`h1` is largest, `h6` is smallest).  
```html
<h1>Main Title</h1>
<h2>Subheading</h2>
```
🔹 **Paragraphs:**  
```html
<p>This is a paragraph.</p>
```
🔹 **Links:**  
```html
<a href="https://google.com">Visit Google</a>
```
🔹 **Images:**  
```html
<img src="image.jpg" alt="Description">
```
---

### **Forms (User Input)**
Forms allow users to enter data like names, emails, and passwords.

```html
<form action="submit.html" method="post">
    <label>Name:</label>
    <input type="text" name="username" required>
    
    <label>Email:</label>
    <input type="email" name="email" required>

    <label>Password:</label>
    <input type="password" name="password" required>

    <button type="submit">Submit</button>
</form>
```
🔹 **`<input>`** - Takes user input (text, email, password, etc.).  
🔹 **`<button>`** - Submits the form.  

---

### **Final Steps**  
✅ Save your file as `.html`.  
✅ Open it in a browser.  
✅ You have created your first webpage! 🚀
"""